const timeline=document.querySelector('#diaryTimeline');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const params=new URLSearchParams(location.search);
let viewYear=Number(params.get('year'))||new Date().getFullYear();
let viewMonth=Number(params.get('month'))||new Date().getMonth()+1;
let allItems=[];
let wheelLocked=false;
const monthNames=['January','February','March','April','May','June','July','August','September','October','November','December'];
const weekdays=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const assetUrl=path=>`/api/v1/assets?path=${encodeURIComponent(path)}`;
const active=item=>item&&!item.deletedAt&&item.day;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0');
const key=(y,m)=>`${y}-${pad(m)}`;
function addMonth(y,m,delta=1){m+=delta;while(m>12){m-=12;y++}while(m<1){m+=12;y--}return[y,m]}
function monthItems(y,m){const prefix=`${key(y,m)}-`;return allItems.filter(active).filter(x=>String(x.day).startsWith(prefix)).sort((a,b)=>(a.ts||0)-(b.ts||0))}
function groupByDay(items){const map=new Map();items.forEach(item=>{if(!map.has(item.day))map.set(item.day,[]);map.get(item.day).push(item)});return map}
function renderCalendar(y,m,items){const grouped=groupByDay(items),first=new Date(y,m-1,1).getDay(),count=new Date(y,m,0).getDate(),name=monthNames[m-1];let days='';for(let i=0;i<first;i++)days+='<span class="day"></span>';for(let d=1;d<=count;d++){const date=`${key(y,m)}-${pad(d)}`,entries=grouped.get(date)||[],images=entries.flatMap(x=>Array.isArray(x.images)?x.images:[]);if(entries.length){days+=images.length?`<a class="day has-memory" href="./day.html?date=${date}" aria-label="Open ${name} ${d}"><img src="${assetUrl(images[0])}" alt=""><span class="num">${d}</span></a>`:`<a class="day has-memory text-memory" href="./day.html?date=${date}" aria-label="Open ${name} ${d}"><span class="text-date">${d}</span></a>`}else days+=`<span class="day">${d}</span>`}
 return `<section class="month-calendar" data-month="${key(y,m)}"><section class="month-intro"><p>${pad(m)} / ${y}</p><h1 data-long-month="${String(name.length>=8)}">${name}</h1><p class="whisper">Some days leave a trace.</p><div class="month-line"><span></span><small>${pad(grouped.size)} memories kept this month</small></div></section><section class="calendar glass-surface" aria-label="${name} ${y} diary calendar"><div class="weekdays"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span></div><div class="days">${days}</div></section><div class="swipe-hint">Swipe sideways for another month</div></section>`}
function formatRecordTime(ts){if(!ts)return'';const d=new Date(ts);return `${pad(d.getHours())}:${pad(d.getMinutes())}`}
function renderShot(path,entry,index){const fallback=formatRecordTime(entry.ts);return `<figure class="memory-shot" data-path="${esc(path)}"><img loading="lazy" src="${assetUrl(path)}" alt="Memory photograph"><figcaption class="photo-time" data-fallback="${esc(fallback)}">Reading capture time…</figcaption></figure>`}
function renderEntry(entry,entryIndex){const images=Array.isArray(entry.images)?entry.images:[];return `<article class="memory-entry"><div class="memory-entry__visual">${images.map((p,i)=>renderShot(p,entry,i)).join('')}</div><div class="memory-entry__copy"><span class="author">${esc(entry.author||'Us')}</span>${entry.text?`<p>${esc(entry.text)}</p>`:''}</div></article>`}
function renderMemories(y,m,items){const grouped=groupByDay(items),name=monthNames[m-1];if(!items.length)return `<section class="month-memories"><header class="month-memories__head"><h2>${name}, quietly.</h2><p>No memory was recorded here yet.</p></header><div class="month-empty">This month is still open.</div></section>`;let body='';[...grouped.entries()].forEach(([date,entries])=>{const [,mm,dd]=date.split('-').map(Number),dt=new Date(y,mm-1,dd);body+=`<section class="memory-day"><aside class="memory-day__date"><strong>${dd}</strong><span>${weekdays[dt.getDay()]} · ${name}</span></aside><div>${entries.map(renderEntry).join('')}</div></section>`});return `<section class="month-memories"><header class="month-memories__head"><h2>${name, name} in frames.</h2><p>Every photograph and every note from this month, in the order they were left behind.</p></header>${body}</section>`}
function renderTimeline(direction=0){const sections=[];let y=viewYear,m=viewMonth;for(let i=0;i<12;i++){const items=monthItems(y,m);sections.push(`<section class="month-section">${renderCalendar(y,m,items)}${renderMemories(y,m,items)}<div class="month-divider"></div></section>`);[y,m]=addMonth(y,m,1)}timeline.innerHTML=sections.join('');document.querySelector('.year').textContent=viewYear;document.querySelector('.bottom-glass span').textContent=`${monthNames[viewMonth-1]} · ${viewYear}`;const first=timeline.querySelector('.month-calendar');if(first&&!reduced){first.style.setProperty('--from-x',direction>0?'55px':'-55px');first.classList.add('is-entering')}bindCalendarNavigation();observeMonths();hydratePhotoTimes();history.replaceState(null,'',`?year=${viewYear}&month=${viewMonth}`)}
function shiftMonth(delta){const [y,m]=addMonth(viewYear,viewMonth,delta);const first=timeline.querySelector('.month-calendar');if(first&&!reduced){first.classList.add(delta>0?'is-leaving-left':'is-leaving-right');setTimeout(()=>{viewYear=y;viewMonth=m;renderTimeline(delta);scrollTo({top:0,behavior:'instant'})},300)}else{viewYear=y;viewMonth=m;renderTimeline(delta);scrollTo(0,0)}}
function bindCalendarNavigation(){document.querySelectorAll('.month-calendar').forEach(calendar=>{let sx=0,sy=0,activePointer=false;calendar.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY;activePointer=true});calendar.addEventListener('pointerup',e=>{if(!activePointer)return;activePointer=false;const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.abs(dx)>64&&Math.abs(dx)>Math.abs(dy)*1.25)shiftMonth(dx<0?1:-1)});calendar.addEventListener('wheel',e=>{if(wheelLocked||Math.abs(e.deltaX)<34||Math.abs(e.deltaX)<=Math.abs(e.deltaY))return;e.preventDefault();wheelLocked=true;shiftMonth(e.deltaX>0?1:-1);setTimeout(()=>wheelLocked=false,700)},{passive:false})})}
const buttons=document.querySelectorAll('.bottom-glass button');buttons[0]?.addEventListener('click',()=>shiftMonth(-1));buttons[1]?.addEventListener('click',()=>shiftMonth(1));
function observeMonths(){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){const [y,m]=entry.target.dataset.month.split('-').map(Number);document.querySelector('.year').textContent=y;document.querySelector('.bottom-glass span').textContent=`${monthNames[m-1]} · ${y}`}}),{threshold:.45});document.querySelectorAll('.month-calendar').forEach(el=>observer.observe(el))}
async function captureTime(path,fallback){try{const res=await fetch(assetUrl(path));if(!res.ok)throw 0;const buf=await res.arrayBuffer();const exif=readExifDate(buf);if(exif)return{label:`Captured · ${exif.slice(11,16)}`,source:'exif'}}catch{}return{label:fallback?`Recorded · ${fallback}`:'Time unavailable',source:'record'}}
function readExifDate(buffer){const v=new DataView(buffer);if(v.byteLength<12||v.getUint16(0)!==0xffd8)return null;let off=2;while(off+4<v.byteLength){if(v.getUint8(off)!==0xff)break;const marker=v.getUint8(off+1),len=v.getUint16(off+2);if(marker===0xe1&&off+2+len<=v.byteLength){const start=off+4;if(v.getUint32(start)===0x45786966){const tiff=start+6,little=v.getUint16(tiff)===0x4949;const u16=p=>v.getUint16(p,little),u32=p=>v.getUint32(p,little);if(u16(tiff+2)!==42)return null;const ifd0=tiff+u32(tiff+4);const exifPtr=findTag(ifd0,0x8769,u16,u32,v,tiff);if(exifPtr){const exifIfd=tiff+exifPtr;const raw=findAsciiTag(exifIfd,0x9003,u16,u32,v,tiff)||findAsciiTag(exifIfd,0x9004,u16,u32,v,tiff);if(raw)return raw.replace(/(\d{4}):(\d{2}):(\d{2})/,'$1-$2-$3')}}} }off+=2+len}return null}
function findTag(ifd,tag,u16,u32,v,tiff){if(ifd+2>v.byteLength)return 0;const n=u16(ifd);for(let i=0;i<n;i++){const p=ifd+2+i*12;if(p+12>v.byteLength)break;if(u16(p)===tag)return u32(p+8)}return 0}
function findAsciiTag(ifd,tag,u16,u32,v,tiff){if(ifd+2>v.byteLength)return null;const n=u16(ifd);for(let i=0;i<n;i++){const p=ifd+2+i*12;if(p+12>v.byteLength)break;if(u16(p)!==tag)continue;const count=u32(p+4),pos=count<=4?p+8:tiff+u32(p+8);if(pos+count>v.byteLength)return null;let s='';for(let j=0;j<count-1;j++)s+=String.fromCharCode(v.getUint8(pos+j));return s}return null}
function hydratePhotoTimes(){const io=new IntersectionObserver(entries=>entries.forEach(async e=>{if(!e.isIntersecting)return;io.unobserve(e.target);const cap=e.target.querySelector('.photo-time');const result=await captureTime(e.target.dataset.path,cap?.dataset.fallback||'');if(cap){cap.textContent=result.label;cap.dataset.source=result.source}}),{rootMargin:'500px'});document.querySelectorAll('.memory-shot').forEach(el=>io.observe(el))}
if(!reduced){const light=document.querySelector('.pointer-light'),world=document.querySelector('.diary-world__image');let tx=0,ty=0,cx=0,cy=0;const animate=()=>{cx+=(tx-cx)*.055;cy+=(ty-cy)*.055;if(light){light.style.left=`${innerWidth*(.5+cx)}px`;light.style.top=`${innerHeight*(.5+cy)}px`}if(world)world.style.transform=`scale(1.09) translate3d(${cx*-1.8}%,${cy*-1.2}%,0)`;requestAnimationFrame(animate)};addEventListener('pointermove',e=>{tx=e.clientX/innerWidth-.5;ty=e.clientY/innerHeight-.5;document.querySelectorAll('.memory-shot').forEach(shot=>{const r=shot.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),near=Math.abs(dx)<r.width*.72&&Math.abs(dy)<r.height*.72;shot.classList.toggle('is-near',near);if(near){shot.style.setProperty('--ry',`${Math.max(-2.4,Math.min(2.4,dx/r.width*3))}deg`);shot.style.setProperty('--rx',`${Math.max(-2,Math.min(2,-dy/r.height*2.5))}deg`)}})},{passive:true});addEventListener('pointerleave',()=>{tx=0;ty=0;document.querySelectorAll('.memory-shot').forEach(s=>{s.classList.remove('is-near');s.style.removeProperty('--rx');s.style.removeProperty('--ry')})});animate()}
async function load(){try{const res=await fetch('/api/v1/notes',{cache:'no-store'});if(res.status===401){location.replace('/?next='+encodeURIComponent(location.pathname+location.search));return}if(!res.ok)throw new Error(`notes_${res.status}`);const data=await res.json();allItems=Array.isArray(data.items)?data.items:[];if(!params.has('year')&&!params.has('month')){const latest=allItems.find(active);if(latest){[viewYear,viewMonth]=latest.day.split('-').map(Number)}}renderTimeline()}catch(err){console.error(err);timeline.innerHTML='<section class="month-empty">Memories are resting for a moment.</section>'}}
load();